<img src="https://numpy.net.cn/doc/stable/_static/numpylogo.svg" alt="NumPy Logo" height="60"><br>

# **NumPy Tutorial**
> [NumPy 中文官方文档](https://numpy.net.cn/doc/stable/index.html)
---
## 1. 基础操作
### 1.1 数组的属性

In [ ]:
import numpy as np
# 创建一个二维数组
a = np.array([[1, 2, 3], [4, 5, 6]])
# 获取数组的属性
print(a.shape)  # 数组的维度，按(rows,cols)，输出: (2, 3)
print(a.size)  # 数组元素的总数，输出: 6
print(a.ndim)  # 数组的轴数（维数），输出: 2
print(a.dtype)  # 数组中元素的数据类型，输出: dtype('int32')
print(a.itemsize)  # 数组中每个元素的字节大小，输出: 4
print(a.nbytes)  # 数组占用的总字节数，输出: 24

### 1.2 创建数组

In [ ]:
import numpy as np
# 创建数组
array_1d = np.array([1, 2, 3]) # 通过list创建数组
array_2d = np.array([[1, 2, 3], [4, 5, 6]],dtype=float) # 通过list创建二维数组,指定元素类型为float
array_zero = np.zeros((3,3),dtype=np.int16) # 创建一个2x3的全0数组,指定元素类型为int16
print(f"array_1d = {array_1d}\narray_2d = \n{array_2d}\narray_zero = \n{array_zero}")
# 创建数字序列（类似于range()函数）
array_range = np.arange(0, 10, 2.5) # 创建一个从0到9，步长为2.5的数组
theta = np.linspace(0, np.pi, 4) # 创建一个从0到π，包含4个元素的数组
array_reshaped = np.arange(6).reshape((3,2)) # 将0到5的数组转换为3x2的数组
print(f"array_range = {array_range}\ncos = {np.cos(theta)}")
print(f"array_reshaped = \n{array_reshaped}")


### 1.3 基本运算
* NumPy数组中的运算符`*`是逐元素相乘，而不是矩阵乘法。要进行矩阵乘法，需要使用`@`运算符(Python >= 3.5)或`np.dot()`函数。
* `+=`和`*=`等运算符用于原地修改数组，而不是创建新数组。
* 常用通用函数`all`, `any`, `apply_along_axis`, `argmax`, `argmin`, `argsort`, `average`, `bincount`, `ceil`, `clip`, `conj`, `corrcoef`, `cov`, `cross`, `cumprod`, `cumsum`, `diff`, `dot`, `floor`, `inner`, `invert`, `lexsort`, `max`, `maximum`, `mean`, `median`, `min`, `minimum`, `nonzero`, `outer`, `prod`, `re`, `round`, `sort`, `std`, `sum`, `trace`, `transpose`, `var`, `vdot`, `vectorize`, `where`

In [ ]:
import numpy as np
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
# 逻辑运算
print(A < 3) # 每个元素是否小于3，返回布尔值数组
# 数组乘法
print(A @ B) # 矩阵乘法，或者使用A.dot(B)或np.dot(A, B)
print(A * B) # 逐元素相乘
print(A**2) # 每个元素的平方
B *= A # *= 操作会修改B数组，而不是创建新数组
print(f"B={B}")
# 常用操作
print(f"sum={A.sum()}")   # 数组所有元素的和
print(f"col_sum={A.sum(axis=0)}") # 每列的和，0-列，1-行
print(f"cum_sum={A.cumsum(axis=0)}") # 每列的累计和，0-列，1-行
print(f"mean={A.mean()}") # 数组所有元素的平均值
print(f"max={A.max()}")   # 数组所有元素的最大值
print(f"min={A.min()}")   # 数组所有元素的最小值
print(f"std={A.std()}")   # 数组所有元素的标准差
print(f"var={A.var()}")   # 数组所有元素的方差
# 通用函数 `ufunc`
print(np.sqrt(A)) # 每个元素的平方根
print(np.exp(A)) # 每个元素的指数
print(np.log(A)) # 每个元素的自然对数
print(np.sin(A)) # 每个元素的正弦值

### 1.4 索引和切片

In [ ]:
import numpy as np
# 一维数组
A = np.array([1,2,3,4,5,6,7,8,9])
print(A[0:5]) # 第0到4个元素，或 A[:5]
print(A[5:]) # 第5个元素到最后一个元素
print(A[::2]) # 每隔一个元素取一个，即第0、2、4、6、8个元素
print(A[::-1]) # 反转数组

# 多维数组
B = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(B[0, :]) # 第0行，或 B[0]
# ...代替:，对于多维数组...表示剩下的所有维度
print(B[1, ...]) # 第1行，或 B[1]
# 用flat迭代器遍历数组所有元素（ravel()函数返回一个展平的一维数组）
for element in B.flat:
    print(element, end=' ')

### 1.5 数组的形状操作

In [ ]:
import numpy as np

A = np.floor(10*np.random.random((3,4))) # 创建一个3x4的随机数组，元素取0-9的整数
print(A)
# 以下操作都会返回一个新的修改了形状的数组，但不改变原数组A
print(A.ravel()) # 展平数组为一维
print(A.reshape(6,2)) # 重塑为6x2的数组
print(A.T) # 转置数组
# 以下操作会修改原数组a的形状
A.resize((2,6)) # 修改数组形状为2x6，或 A.resize((2,-1))，-1表示自动计算该维度大小
print(A)
A.shape = (6,2) # 直接修改shape属性也可以修改数组形状
print(A)
# 数组拼接
B = np.floor(10*np.random.random((3,4)))
C = np.floor(10*np.random.random((3,4)))
print(np.vstack((B, C))) # 垂直堆叠数组
print(np.hstack((B, C))) # 水平堆叠数组

[[8. 3. 0. 6.]
 [8. 8. 2. 0.]
 [1. 3. 6. 9.]]
[8. 3. 0. 6. 8. 8. 2. 0. 1. 3. 6. 9.]
[[8. 3.]
 [0. 6.]
 [8. 8.]
 [2. 0.]
 [1. 3.]
 [6. 9.]]
[[8. 8. 1.]
 [3. 8. 3.]
 [0. 2. 6.]
 [6. 0. 9.]]
[[8. 3. 0. 6. 8. 8.]
 [2. 0. 1. 3. 6. 9.]]
[[8. 3.]
 [0. 6.]
 [8. 8.]
 [2. 0.]
 [1. 3.]
 [6. 9.]]
[[7. 5. 4. 9.]
 [9. 0. 8. 8.]
 [5. 2. 1. 8.]
 [5. 1. 8. 8.]
 [9. 6. 0. 2.]
 [6. 6. 3. 6.]]
[[7. 5. 4. 9. 5. 1. 8. 8.]
 [9. 0. 8. 8. 9. 6. 0. 2.]
 [5. 2. 1. 8. 6. 6. 3. 6.]]
